### ISSUE TITLE
FATAL ERROR Replace https://localhost:6443 by https://master-ip:6443] 

### ISSUE THREAD

**Issue by mendevi** [k3s-io/k3s-ansible#100] opened 2020-11-16 00:35 UTC
The error I receive is below. It does not matter which node I choose as the Master (I have tried all 6 of my Raspberry Pi's). Or what version of K3s I try and run (I've done 1.19.3+k3s3, 1.19.3+k3s2, 1.18.12+k3s1 etc.)
The crazy thing is I had this up and running 3 days ago with no issues.

TASK [k3s/master : Replace https://localhost:6443 by https://master-ip:6443] *******************************************
Sunday 15 November 2020  19:15:44 -0500 (0:00:01.027)       0:01:28.650 *******
fatal: [192.168.4.12]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'master' is undefined\n\nThe error appears to be in '/home/ublaptop/k3s-ansible/roles/k3s/master/tasks/main.yml': line 62, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Replace https://localhost:6443 by https://master-ip:6443\n  ^ here\n"}

my hosts.ini looks like below
____________________________________
[master]
192.168.4.11

[node]
192.168.4.12
192.168.4.13
192.168.4.14
192.168.4.15
192.168.4.16

[k3s_cluster:children]
master
node
______________________________________________
and my group_vars all.yml below

k3s_version: v1.18.12+k3s1
ansible_user: ubuntu
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: ""
extra_agent_args: ""

**Comment by Siete-de-Nueve** [comment] 2020-12-26 10:29
i have same problem.

--------

fatal: [192.168.1.88]: FAILED! => {"attempts": 20, "changed": false, "cmd": ["k3s", "kubectl", "get", "--raw", "/api/v1/nodes/"], "delta": "0:00:01.399466", "end": "2020-12-24 13:42:11.263038", "msg": "non-zero return code", "rc": 1, "start": "2020-12-24 13:42:09.863572", "stderr": "The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?", "stderr_lines": ["The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?"], "stdout": "", "stdout_lines": []}

----

192.168.1.88 is master node ip

**Comment by Billdapart** [comment] 2021-06-17 17:45
Having the same issue and can't track down the cause. Installation looks like everything works. Kubectl shows a client running fine, no server found. Try to get nodes and it looks for server at localhost

**Comment by selste** [comment] 2021-09-15 06:01
I'm experiencing the same issue.
Running the playbook on a RHEL 7 VM with K3s v1.21.4+k3s1 results in

> TASK [k3s/master : Replace https://localhost:6443 by https://master-ip:6443] ****************************************************************************************************************************************************************
Wednesday 15 September 2021  07:44:38 +0200 (0:00:00.647)       0:00:48.477 ***
fatal: [master-ip]: FAILED! => {"changed": true, "cmd": "k3s kubectl config set-cluster default --server=https://master-ip:6443 --kubeconfig /home/dummy/.kube/config", "msg": "[Errno 2] No such file or directory", "rc": 2}

Running the command manually - as the 'dummy' user - on the target host right after the playbook failed works just fine.

**Comment by dereknola** [comment] 2023-11-09 17:20
Resolved with https://github.com/k3s-io/k3s-ansible/pull/143

**Closed by dereknola** 2023-11-09 17:20 UTC
